apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-svc
  labels:
    app: {{ template "fullname" . }}
    component: {{ template "fullname" .}}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - port: {{ default 8080 .Values.server.servicePort }}
  selector:
    app: {{ template "fullname" . }}
  type: LoadBalancer
