---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHMAAABzCAYAAACrQz3mAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAABINJREFUeNrs3UtIVFEcBvA7PhKDjKggqDbVwh62SEqCUHPhJpUeLiLJCoJK2rTSdlGLHlBLbRdEtckSLAqk1B4EtihKeyyUEGxlYGNmpOn0nTyggsnMOHPv+f/v98Hh6sK5jx/fnTvXOTORWCzmMTqSwUNATMbBZM38JRKJqNvBof7tZqcaMU76dlDfjnRlfv1d5Nf6cuv6IuqbGQSkM81UBpmJxQ2Mw6E8zSqDvIlxKLTPmUogF2FxB+NAqC+AlEA2Y1TypYlsyMVY3A8rpJpmWsiHGLt500A25BJCKmgmIJdi0Yaxw2PkNpOQSpoJyJVYPMUoIKFgTAvZjrGFfIJPs4Bcg8VzQgpvpoXsxFhPNsHNBOQGQipo5gzI1eQS3ExA5hNSQTMBWWCvWleQSXAzAbmVkAowAWneO/OCkMIxLaS5RZdHGsGYgCzD4gkhhV8AWUjzb6xckghuJiD3EFJBMwFZ5U29ZyebFIIx73UfL/S8d6fx4yt1p7tI1rCX8edDKDDzWj/WHPvirRuu2lSusSHjLWXnvFX+v7EsIwBI8w5z8wblTJ4YBWMC8pSF5OwzyZgWspGHXDgmIOsJqQATkA1YXOKhFo4JyPNYXORhFv7SBJCmjfU8xIIxgWhmK1/FOMPDKxjTQoZm2rna50xAmpsATYQU3kwLGbpp5+qaSUglzQSkmXZ+F6OKh1IwpoUM7ecHqMEEpJl23oJRzkMoGNNCctq59AsgQJrZyo8IKbyZFpLTzqU3E5DLCamgmYDktHMNzSSkkmYCktPONTSTkEowAWmmnb8kpPDTrIU0jeS0cwXNJKS8fP0fJiHlQZYmdNOAcTL9BjJ7X3tv3DcNGCfTZyEH4r5pwMiBJKa89GDsnAuSmPIgywA5GPdNA8bJvMYomQ+SF0ByIMsBGU30pgHjVp7FC8lmup0OjApAjsb7B2ymm2lLFJKYbuYBRmWikMR0L60Y1YAcS+aPielOzNdE7k8WkphuQdYCcmIhD0LM4HM9FZB8aeIGZB0gY6l4MDYzuFxLJSSbGVwuA7Eh1Q/KZvqfC+mAZDP9z1lApu3TyojpX+oBeSWdKyCmPzEXOk3pXgmfM5VAspnpzSTGEUDe8muFxExPzN0cc1fntp8rnYWZ0/Pdt0/837g2b1vN56FOhZBjj392N1QVFr/xe8WzMCPjk5v9WnHOhDeCRZEyyHGM6iAgeQGU2vzC2Hsif1lrUBvA58zUQVYAsj3IjWAzF54fLkCymQvPMEY5ILtc2Bg2M/lEXYJkM5PPN4wyQHa7tFFsphJIYiYeM+18l4uQPM0mDlkKyF5XN5DNjC9mtnKJy5BsZvyQppEDrm8omzl/PkmBZDPnT4+9ah2UssFs5tx5Lw2SmHPHTDsvlgZJzLkhzS26qMSNJ+Z0OuypNSp1B3gBNA1p/o01Knkn2MypL9wRD8lmTn1+QDUgxzTsTJib2awJMsyYZtr5QU2QYcU0X9xaC8gJbTsWNkwz7fyoRsiwYf77/ABAxrTuYCQWi3kMm8kQkyEmQ8ww5a8AAwCH20kjn1l8pwAAAABJRU5ErkJggg==
    marketplace.cloud.google.com/deploy-info: '{partner_id: "aquasecurity-public", product_id: "aqua-container-security", partner_name: "Aqua Security Software Inc."}'
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: Aqua Container Security Platform
    version: '0.1.4'
    description: |-
      Aqua's Container Security Platform provides full visibility into container activity, allowing organizations to detect and prevent suspicious activity and attacks, providing transparent, automated security while helping to enforce policy and simplify regulatory compliance.
      ## Support
      [Email Aqua Support](mailto:support@aquasec.com?cc=cloud.sales@aquasec.com&Subject=GKE%20Marketplace%20Support%20Question%20Customer%20ID&Body=Dear%20Aqua%20support,)


    maintainers:
    - name: Aqua Security
      url: https://www.aquasec.com
    links:
    - description: Getting Started with Aqua Security for GKE
      url: https://gcp-mktplace-docs.aquasec.com/     
    notes:  |-
      The marketplace deployer will automatically deploy the Aqua Command Center and accompanying Aqua Enforcers set to audit mode. This process takes approx. three minutes. The following four basic steps are necessary to complete deployment:
    
      ### 1. Backup Auto-Generated Secrets
      By default the Aqua postgresql container utilizes a persistant volume (PVC). This PVC is not deleted along with your application in order to save your data.
      In the case you re-deploy using the same application name and namespace, reloading these secrets will be necessary to access the db files on the reused PVC.
      Please back them up now and see the getting started guide for more detail.
      ```shell
      kubectl get secrets -l secretType=aquaSecurity \
      --namespace {{ .Release.Namespace }} -o json > aquaSecrets.json
      ```

      ### 2. Obtain the Aqua Command Center portal information:
      A user may run the following command or click on the Services tab and look for {{ .Release.Name }}-server-svc.
      ```shell
      SERVICE_IP=$(kubectl get svc {{ .Release.Name }}-server-svc \
      --namespace {{ .Release.Namespace }} \
      --output jsonpath='{.status.loadBalancer.ingress[0].ip}')
      echo "http://${SERVICE_IP}:8080"
      ```

      ### 3. Obtain the Aqua Command Center administrator password
      The default username is `administrator`. Use `kubectl` to extract the generated password from the secret.
      ```shell
      kubectl get secret {{ .Release.Name }}-admin-pass \
      --namespace {{ .Release.Namespace }} \
      --output=jsonpath='{.data.password}' | base64 --decode
      ```

      ### 4. Enter the license to enable the product
      Users that have a license token for GKE Marketplace should enter it to enable the PAYG billing of Enforcers. If you do not have a license token, you may request one by filling out the form [here.](https://www.aquasec.com/aqua-signup/?type=marketplace-gke)

      ### View logs of the Aqua Command Center
      Should you need to access logs of the Aqua server pod, use the below command.
      ```shell
      SERVERPOD=$(kubectl get pods -l app={{ .Release.Name }}-server \
      --namespace {{ .Release.Namespace }} --no-headers -o=custom-columns=NAME:.metadata.name)
      kubectl logs -f ${SERVERPOD} --namespace={{ .Release.Namespace }}
      ```
     
  info:
  - name: Aqua Command Center Service
    type: Reference
    valueFrom:
      serviceRef:
        name: "{{ .Release.Name }}-svc"
  selector:
    matchLabels:
        app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: apps/v1beta2
    kind: Deployment
  - group: v1
    kind: Service
  - group: v1
    kind: DaemonSet

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-db-secret"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    secretType: aquaSecurity
type: Opaque
data:
  password: "{{.Values.dbPassword}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-enforcer-token"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    secretType: aquaSecurity
type: Opaque
data:
  password: "{{.Values.enforcerToken}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-admin-pass"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    secretType: aquaSecurity
type: Opaque
data:
  password: "{{.Values.adminPassword}}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-database-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
