apiVersion: v1
description: Secure your container deployment
name: aqua
version: 3.2
home: aquasec.com
keywords:
- aqua
- container
- security
- least privilege
maintainers:
- email: johnm@aquasec.com
  name: John Michealson
